server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: douaa1234
    key-store-type: PKCS12

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pigeonskyv3
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: pigeonSkyClientId
            client-secret: DFJVAIO6XFJz6C0oV225cY3KkH8VEdrI
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: https://localhost:8443/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/pigeonSkyV3


  management:
    endpoints:
      web:
        exposure:
          include: health, info, metrics, env, uptime
    endpoint:
      health:
        show-details: always
        group:
          live:
            include: uptime, db, diskspace, heap
    security:
      enabled: false

keycloak:
  auth-server-url: "https://localhost:8443/auth"
  realm: pigeonSkyV3
  resource: springboot-app
  credentials:
    secret: pigeonSkyClientId
  use-resource-role-mappings: true
  public-client: false
  bearer-only: true



logging:
  level:
    root: INFO
    keycloak: DEBUG
    org.springframework.security: INFO
    org.keycloak: WARN
